CREATE DATABASE QUANLYVBUS;
-- 1. Bảng Phân quyền
create table PHANQUYEN
(
	IDROLE CHAR(5) primary KEY not null,
    ROLENAME nvarchar(30) 
);
-- 2. Bảng Người dùng
create table NGUOIDUNG
(
	IDUSER CHAR(5) PRIMARY KEY NOT NULL,
    TENDN NVARCHAR(30),
    MKHASH NVARCHAR(30),
    HOTEN nvarchar(30),
    TRANGTHAIND enum('HOẠT ĐỘNG','NGƯNG HOẠT ĐỘNG'),
    foreign key (IDROLE) references  AUTHOR(IDROLE)
);

-- 3. Bảng Tuyến xe (Gộp Nội thành & Ngoại thành)
CREATE TABLE TUYENXE (
    IDTUYEN CHAR(5) PRIMARY KEY NOT NULL,
    TENTUYEN NVARCHAR(100) NOT NULL,
    DIEMDI NVARCHAR(100),
    DIEMDEN NVARCHAR(100),
    KHOANGCACH int,
    LOAITUYEN NVARCHAR(20) 
);

-- 4. Bảng Xe buýt
create table XEBUS
(
	BUSID CHAR(5) primary key not null,
    BIENSO char(10),
    SOGHE int,
    LOAIGHE enum('NẰM','NGỒI'),
    TRANGTHAIXE enum('ĐANG CHẠY','BÃO DƯỠNG')
);

-- 5. Bảng Chuyến xe (Lịch chạy cụ thể)
CREATE TABLE CHUYENXE (
    IDCHUYEN CHAR(5) PRIMARY KEY NOT NULL,
    FOREIGN KEY (IDTUYEN) REFERENCES TUYENXE(IDTUYEN),
    FOREIGN KEY (IDBUS) REFERENCES XEBUS(IDBUS),
    DepartureTime DATETIME NOT NULL,
    ArrivalTime DATETIME,
    Status NVARCHAR(20) DEFAULT 'Scheduled'
);

-- 6. Bảng Chính sách ưu đãi
CREATE TABLE UUDAI (
    IDKM CHAR(5) PRIMARY KEY NOT NULL,
    MAKM VARCHAR(20) UNIQUE NOT NULL,
    CHIETKHAU DECIMAL(18,2),
    NGAYBD DATE,
    NGAYKT DATE
);

-- 7. Bảng Đặt xe
CREATE TABLE DATXE (
    IDDATXE CHAR(5) PRIMARY KEY NOT NULL,
	FOREIGN KEY (IDUSER) REFERENCES NGUOIDUNG(IDUSER),
    FOREIGN KEY (IDCHUYEN) REFERENCES CHUYENXE(IDCHUYEN),
    FOREIGN KEY (IDKM) REFERENCES UUDAI(IDKM),
    NGAYDAT date,
    SOGHE VARCHAR(10),
	TONGTIEN DECIMAL(18,2),
    TIENCONLAI decimal(18,2),
    TTTHANHTOAN NVARCHAR(20) DEFAULT 'Pending'
);

-- 8. Bảng Đánh giá & Phản hồi 
CREATE TABLE DANHGIA (
    IDDG CHAR(5) PRIMARY KEY NOT NULL,
    FOREIGN KEY (IDUSER) REFERENCES NGUOIDUNG(IDUSER),
      FOREIGN KEY (IDCHUYEN) REFERENCES CHUYEXE(IDCHUYEN),
    DANHSAO INT CHECK (DANHSAO >= 1 AND DANHSAO <= 5),
    NOIDUNG NVARCHAR(MAX),
    NGAYDG DATETIME DEFAULT GETDATE()
);

-- 9. Bảng Chatbot AI
CREATE TABLE CHATBOT (
    IDLOG CHAR(5) PRIMARY KEY NOT NULL,
	FOREIGN KEY (IDUSER) REFERENCES NGUOIDUNG(IDUSER),
    CAUHOI NVARCHAR(MAX),
    TRALOI NVARCHAR(MAX),
    NGAYCHAT DATETIME DEFAULT GETDATE()
);
-- 10. Bảng tài xế
-- 11. Bảng thanh toán
-- 12. Bảng hỗ trợ
